version: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: geolog-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: geolog-backend
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MONGODB_URI: "mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: geolog-frontend
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "5173:5173"
    env_file:
      - ./frotend/.env
    environment:
      VITE_API_URL: http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:
